// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BeatmapDownloader.Database.Database;

namespace BeatmapDownloader.Database.Migrations
{
    [DbContext(typeof(BeatmapDownloaderDatabaseContext))]
    [Migration("20200704040633_InitializeMigration")]
    partial class InitializeMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("MultiplayerDownloader.WpfUI.Model.DownloadBeatmapSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeatmapSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadProviderName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DownloadTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadProviderId");

                    b.HasIndex("DownloadProviderName");

                    b.ToTable("DownloadedBeatmapSets");
                });
#pragma warning restore 612, 618
        }
    }
}
